### ISSUE TITLE
Comment renseigner une observation dans le cas d'un manquant ? 

### ISSUE THREAD

**Issue by Sylvain** [24eme/vinsdeloire#3]
Bonjour, 

dans le cas d'un mouvement de type Excédent / Manquant, il est demandé de spécifier le champ Observation, c'est d'ailleurs également demandé sur Prodouane. Mais le champ Observation est dans la même colonne que le champ Quantité. Comment puis je indiquer une quantité de manquant et la raison de ce manquant ? 

Je vous remercie par avance.

**Comment by teymour** [comment]
Bonjour,

Merci pour votre question.

Nous abordons la question des observations, dans la documentation dans la section « cas des informations complémentaires » :
https://github.com/24eme/mutualisation-douane/tree/master/logiciels-tiers#cas-des-informations-compl%C3%A9mentaires

Un exemple est disponible dans le csv CAVE fourni avec le documentation. Le cas de l'observation est en ligne 19 : 
https://github.com/24eme/mutualisation-douane/blob/master/logiciels-tiers/exemple_cave.csv#L19

En espérant que ça vous permette de comprendre le format CSV/DRM

**Comment by Sylvain** [comment]
Parfait, bien compris, je vous remercie.
